schema: http://localhost:4000/graphql
overwrite: true
generates:
  ./src/fns/graphql/types.d.ts:
    plugins:
      - time
      - add: '// REGENERATE THIS BY STARTING THE LOCAL SERVER'
      - add: '// AND THEN RUNNING `back % yarn generate`'
      - add: ''
      - typescript-common
      - typescript-server
      - typescript-resolvers
